PoC/UI-MVC/Controllers/IoTController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using PoC.Domain.iot;
using Microsoft.AspNetCore.Mvc;
using PoC.BL.manager.input;
using PoC.BL.manager.iot;

namespace PoC.Controllers
{
    
    [Route("{org}/[controller]")]
    public class IoTController : Controller
    {
        private readonly IIotManager _mgr;
        public IoTController(IIotManager mgr)
        {
            _mgr = mgr;
            }
        // GET
        [Route("manageiot")]
        public IActionResult ManageIoT()
        {
            List<Poster> posters = _mgr.GetPosters();
            return View(posters);
        }

        [HttpGet]
        [Route("addPoster")]
        [Authorize(Roles = "Admin")]
        public IActionResult AddPoster()
        {
            return View();
        }

        [HttpPost]
        [Route("addposter")]
        public IActionResult AddPoster(IFormCollection formValues)
        {
            Poster p = _mgr.MakePosterFromForm(formValues);
            
            return RedirectToAction("ManageIoT");
        }
        
        [HttpGet]
        [Route("/[controller]/addvote/{button}")]
        public void AddVote(string button)
        {
            Console.WriteLine(button);
            _mgr.AddVote(button);
        }

        [HttpGet]
        [Route("editposter/{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Editposter(string id)
        {

            return View(_mgr.GetPoster(id));
        }
        
        [HttpPost]
        [Route("editposter/{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Editposter(string id, IFormCollection formValues)
        {
            Poster p = _mgr.GetPoster(id);
            _mgr.ChangePosterFromForm(p, formValues);
            return RedirectToAction("manageiot");
        }
        
        [Route("deactivateposter/{id}")]
        [Authorize(Roles = "Admin")]
        public void DeactivatePoster(string id)
        {
            Poster poster = _mgr.GetPoster(id);

            _mgr.ClosePoster(poster);
        }

        [HttpGet]
        [Route("viewPoster/{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Viewposter(string id)
        {
            Poster p = _mgr.GetPoster(id);
            return View(p);
        }
    }
}

PoC/UI-MVC/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PoC.BL.manager.InputMethod;
using PoC.BL.manager.organisation;
using PoC.BL.manager.project;
using PoC.BL.manager.user;
using PoC.Domain.input;
using PoC.Domain.inputmethod;
using PoC.Domain.organisation;
using PoC.Domain.project;
using PoC.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace PoC.Controllers
{
  //[Authorize(Roles = "SuperAdmin")]
  [Route("{org}/projecten")]
  public class ProjectController : Controller
  {
    private readonly IProjectManager _mgr;
    private readonly IOrganisationManager _organisationManager;
    private readonly IInputMethodManager _inputmgr;
    private readonly IUserManager _userManager;

    //File Management
    private readonly IHostingEnvironment _hostingEnvironment;


    public ProjectController(IProjectManager mgr, IInputMethodManager inputmgr,
      IHostingEnvironment hostingEnvironment, IOrganisationManager organisationManager,
      IUserManager userManager)
    {
      _mgr = mgr;
      _inputmgr = inputmgr;
      _hostingEnvironment = hostingEnvironment;
      _organisationManager = organisationManager;
      _userManager = userManager;
    }


    private IEnumerable<Project> SortProjects(string org)
    {
      IEnumerable<Project> projects = _organisationManager.GetOrganisationByName(org.ToUpper()).Projects;
      var projs = new List<Project>();
      foreach (var project in projects)
      {
        var proj = _mgr.GetProject(project.Id);
        projs.Add(proj);
      }

      projs.ToList().Sort((p1, p2) => p1.Begin.CompareTo(p2.Begin));

      return projs;
    }

    // GET
    [HttpGet]
    public IActionResult Index(string org)
    {
      ViewData["projectImage"] = org;

      IEnumerable<Project> projects = SortProjects(org);
      return View(projects);
    }


    [HttpGet]
    [Route("/{org}/projecten/Detail/{id}")]
    public IActionResult Detail(string org, string id)
    {
      ViewData["projectImage"] = org;

      Project proj = _mgr.GetProject(id);
      //NullReferenceException: Object reference not set to an instance of an object.
      //PoC.Controllers.ProjectController.Detail(string id) in ProjectController.cs, line 50 bij Edit
      foreach (var pastfase in proj.PastFases)
      {
        List<InputMethod> list = new List<InputMethod>();
        foreach (InputMethod method in _mgr.GetInputMethodsOfFase(pastfase.Id)) list.Add(method);
        pastfase.InputMethods = list;
      }

      List<InputMethod> list1 = new List<InputMethod>();
      foreach (InputMethod method in _mgr.GetInputMethodsOfFase(proj.CurrentFase.Id)) list1.Add(method);
      proj.CurrentFase.InputMethods = list1;
      return View(proj);
    }

    [Route("/projecten/addLikeToProject/{pid}/{uid}")]
    public void addLikeToProject(string pid, string uid)
    {
      _mgr.AddLikeToProject(_mgr.GetProject(pid), _userManager.GetUser(uid));
    }

    [Route("/projecten/addShareToProject/{pid}")]
    public void AddShareToProject(string pid)
    {
      _mgr.AddShareToProject(_mgr.GetProject(pid));
    }

    [HttpPost]
    [Route("Detail/{id}")]
    public IActionResult Detail(IFormCollection formData, string id, string org)
    {
      QuestionList questionList = _mgr.GetQuestionList(formData["listId"]);
      List<Question> questions = questionList.Questions.ToList();
      List<Answer> answers = new List<Answer>();
      ViewData["projectImage"] = org;
      

      foreach (var question in questions)
      {
        var t = formData[question.id].Count;
        if (t != 0)
        {
          answers = question.Awnsers.ToList();
          foreach (var value in formData[question.id])
          {
            answers.Add(new Answer(value));
            question.Awnsers = answers;
          }

          _inputmgr.ChangeQuestion(question);
        }
      }

      var p = _mgr.GetProject(id);
      return View(p);
    }
    [HttpGet]
    [Route("SearchProjects")]
    public IActionResult SearchProjects()
    {
      List<Project> searchProjects = new List<Project>();
      return View(searchProjects);
    }
    
     
    [HttpPost]
    [Route("SearchProjects")]
    public IActionResult SearchProjects(string org, string keywordProjects)
    {
      ViewData["organisation"] = org;
      List<Project> searchProjects = new List<Project>();
      if (keywordProjects != null)
      {
        IEnumerable<Project> projects = SortProjects(org);
        searchProjects = projects.Where(project =>
          project.Name.ToLower().Replace(" ", "").Contains(keywordProjects.ToLower().Replace(" ", ""))).ToList();
      }

      return View(searchProjects);
    }
    // Admin
    [Authorize(Roles = "Admin, SuperAdmin")]
    [HttpGet]
    [Route("ManageProjects")]
    public IActionResult ManageProjects(string org)
    {
      IEnumerable<Project> projects = SortProjects(org);

      return View(projects);
    }

    [HttpGet]
    [Route("EditProject/{id}")]
    public IActionResult EditProject(string id)
    {
      Project project = _mgr.GetProject(id);
      return View(project);
    }

    [HttpPost]
    [Route("EditProject/{id}")]
    public IActionResult EditProject(string org, Project project, IFormFile imageProject)
    {
      if (!ModelState.IsValid)
      {
        if (ModelState["Begin"].Errors.Count == 1)
        {
          ModelState["Begin"].Errors.Clear();
          ModelState.AddModelError("Begin", "Begindatum verplicht in te vullen");
        }

        if (ModelState["End"].Errors.Count == 1)
        {
          ModelState["End"].Errors.Clear();
          ModelState.AddModelError("End", "Einddatum verplicht in te vullen");
        }

        if (ModelState["CurrentFase.Begin"].Errors.Count == 1)
        {
          ModelState["CurrentFase.Begin"].Errors.Clear();
          ModelState.AddModelError("CurrentFase.Begin", "Begindatum Fase verplicht in te vullen");
        }

        if (ModelState["CurrentFase.End"].Errors.Count == 1)
        {
          ModelState["CurrentFase.End"].Errors.Clear();
          ModelState.AddModelError("CurrentFase.End", "Einddatum Fase verplicht in te vullen");
        }

        return View(project);
      }

      if (imageProject != null)
      {
        if (ExtensionMethods.FileManagement.CheckFileExtension(imageProject.FileName))
        {
          {
            var projectOrgstring = "organisations/" + org + "/organisation/projects/images";
            var fileName = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,projectOrgstring, imageProject);
            project.ImageName = fileName;
          }
        }
      }

      _mgr.ChangeProject(project);
      return RedirectToAction("ManageProjects");
    }

    // Methode renamen naar Afsluiten/Heropstarten (?)
    [HttpPost]
    [Route("DeleteProject/{id}")]
    public void DeleteProject(string id)
    {
      Project project = _mgr.GetProject(id);


      _mgr.CloseProject(project);
    }


    [HttpGet]
    [Route("CreateProject")]
    public IActionResult CreateProject()
    {
      return View();
    }

    [HttpPost]
    [Route("CreateProject")]
    public IActionResult CreateProject(string org, ProjectViewModel projectViewModel)
    {
      if (!ModelState.IsValid)
      {
        if (ModelState["Begin"].Errors.Count == 1)
        {
          ModelState["Begin"].Errors.Clear();
          ModelState.AddModelError("Begin", "Begindatum verplicht in te vullen");
        }

        if (ModelState["End"].Errors.Count == 1)
        {
          ModelState["End"].Errors.Clear();
          ModelState.AddModelError("End", "Einddatum verplicht in te vullen");
        }

        if (ModelState["Fase.Begin"].Errors.Count == 1)
        {
          ModelState["Fase.Begin"].Errors.Clear();
          ModelState.AddModelError("Fase.Begin", "Begindatum Fase verplicht in te vullen");
        }

        if (ModelState["Fase.End"].Errors.Count == 1)
        {
          ModelState["Fase.End"].Errors.Clear();
          ModelState.AddModelError("Fase.End", "Einddatum Fase verplicht in te vullen");
        }

        return View(projectViewModel);
      }

      var fileName = "";
      if (ExtensionMethods.FileManagement.CheckFileExtension(projectViewModel.ImageCreateProject.FileName))
      {
        var projectOrgstring = "organisations/" + org + "/organisation/projects/images";
        fileName = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,projectOrgstring, projectViewModel.ImageCreateProject);
      }

      Organisation organisation = _organisationManager.GetOrganisationByName(org.ToUpper().Replace(" ", ""));

      Project project = _mgr.AddProjectViewModel(projectViewModel.Name, fileName,
        projectViewModel.MainQuestion, projectViewModel.Description, projectViewModel.Category, projectViewModel.Begin,
        projectViewModel.End, projectViewModel.Fase.FaseName, projectViewModel.Fase.ProjectFase,
        projectViewModel.Fase.Begin, projectViewModel.Fase.End);

      _organisationManager.AddProjectToOrganisation(organisation, project);

      return RedirectToAction("Detail", new {id = project.Id});
    }

    [HttpGet]
    [Route("CreateFaseProject/{id}")]
    public IActionResult CreateFaseProject()
    {
      return View();
    }

    [HttpPost]
    [Route("CreateFaseProject/{id}")]
    public IActionResult CreateFaseProject(string id, FaseViewModel faseViewModel)
    {
      Project project = _mgr.GetProject(id);

      if (!ModelState.IsValid)
      {
        if (ModelState["Begin"].Errors.Count == 1)
        {
          ModelState["Begin"].Errors.Clear();
          ModelState.AddModelError("Begin", "Begindatum verplicht in te vullen");
        }

        if (ModelState["End"].Errors.Count == 1)
        {
          ModelState["End"].Errors.Clear();

PoC/UI-MVC/Views/Shared/_IdeationPartial.cshtml
@model PoC.Domain.inputmethod.Ideation
    <div class="card w-100 disableBorder" id="contactBackground">
        @if (Model.HideIdeation) {
            <h4 style="font-weight: bold">Afgesloten Ideation</h4>
        }
        <p class="card-header" id="contactHeaders">
           @Model.TitleIdeation
        </p>
        <div class="card-body">
            <p>@Model.DescriptionIdeation</p>
            <a class="btn btn-primary" asp-controller="Ideation" asp-action="Index" asp-route-id="@Model.Id">Geef jouw mening of idee</a>
        </div>
    </div>
<br/>

PoC/UI-MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Identity
@using PoC.Areas.Identity.Data
@inject SignInManager<PoCIdentityUser> SignInManager
@inject UserManager<PoCIdentityUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - City of Ideas</title>

    <link rel="stylesheet" href="~/dist/site.css"/>
    <script type="module" src="~/dist/site.entry.js" defer></script>


</head>
<body>
<nav class="navbar navbar-expand sticky-top" id="navbar">
    <a class="navbar-brand" id="logo" href="/">
        <img alt="Brand" src="/images/logo.png">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            @if (!Context.Request.GetDisplayUrl().Contains("Identity"))
            {
                <form class="form-inline my-2 my-lg-0" asp-controller="Project" asp-action="SearchProjects" method="post">
                    <input class="form-control mr-sm-2" type="search" name="keywordProjects" placeholder="Zoek projecten" aria-label="Search">
                    <input value="Zoek" type="submit" class="btn btn-primary submitsearch"/>
                </form>
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Project" asp-action="Index">Projecten</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                </li>
            }
            @if (Context.Request.GetDisplayUrl().Contains("Identity"))
            {
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
            }
        </ul>
        <partial name="_LoginPartial"/>
    </div>
</nav>


<div class="container">
    <div class="row">
        <div class="col-xs-offset 1 col-xs-11 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
            <div class="btn-toolbar" role="toolbar">
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Moderator") || User.IsInRole("Admin") || User.IsInRole("SuperAdmin")))
                        {
                            if (!Context.Request.GetDisplayUrl().Contains("superadmin"))
                            {
                                <a id="list" class="btn btn-primary" title="Moderator" asp-controller="Moderator" asp-action="Index">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                            }
                        }
                    </div>
                    <div class="btn-group" role="group">
                        @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin")) || User.IsInRole("SuperAdmin"))
                        {
                            string orgLink = "";
                            if (@TempData["Orglink"] != null)
                            {
                                orgLink = @TempData["Orglink"].ToString();
                            }
                            string manageProjecten = "/" + orgLink + "/projecten/ManageProjects";
                            string iotOpstelling = "/" + orgLink + "/IoT/manageiot";
                            string moderator = "/" + orgLink + "/Moderator";
                            string manageModerator = "/" + orgLink + "/Admin/ManageModerators";
                            string manageUsers = "/" + orgLink + "/Admin/ManageUsers";
                            if (!Context.Request.GetDisplayUrl().Contains("superadmin"))
                            {
                                <a id="list" class="btn btn-primary" title="Users beheren" asp-controller="Admin" asp-action="ManageUsers">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                                <a id="list" class="btn btn-primary" title="Moderators beheren" asp-controller="Admin" asp-action="ManageModerators">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                                <a id="list" class="btn btn-primary" title="Projecten beheren" asp-controller="Project" asp-action="ManageProjects">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                                <a id="list" class="btn btn-primary" title="IoT Opstelling" asp-controller="IoT" asp-action="ManageIoT">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a> 
                            }
                            if (Context.Request.GetDisplayUrl().Contains("superadmin"))
                            {
                                <a id="list" class="btn btn-primary" title="Moderator" href="@moderator">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                                <a id="list" class="btn btn-primary" title="Users beheren" href="@manageUsers">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                                <a id="list" class="btn btn-primary" title="Moderators beheren" href="@manageModerator">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                                <a id="list" class="btn btn-primary" title="Projecten beheren" href="@manageProjecten">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                                <a id="list" class="btn btn-primary" title="IoT Opstelling" href="@iotOpstelling">
                                    <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                                </a>
                            }
                            
                        }
                    </div>
                    <div class="btn-group" role="group">
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
                        {
                            <a id="list" class="btn btn-primary" title="Admins beheren" asp-controller="SuperAdmin" asp-action="ManageAdmins">
                                <i class="fas fa-tools fa-lg" aria-hidden="true"></i>
                            </a>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<partial name="_CookieConsentPartial"/>

<div class="container">
    @RenderBody()
    <hr/>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center">
                    <p><a>City of Ideas</a> is een geregistreerde website, opgesteld volgens de laatste richtlijnen. </p>
                    <p class="h6">&copy; 2019 - City of Ideas</p>
                </div>
            </div>
        </div>
    </footer>
</div>


@RenderSection("Scripts", required: false)
</body>
</html>

PoC/UI-MVC/Views/Shared/_Layout404.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Identity
@using PoC.Areas.Identity.Data
@inject SignInManager<PoCIdentityUser> SignInManager
@inject UserManager<PoCIdentityUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - City of Ideas</title>

    <link rel="stylesheet" href="~/dist/site.css"/>
    <script type="module" src="~/dist/site.entry.js" defer></script>


</head>
<body>
<nav class="navbar navbar-expand sticky-top" id="navbar">
    <a class="navbar-brand" id="logo" href="/">
        <img alt="Brand" src="/images/logo.png">
    </a>
    <h1 style="margin-left: 35%;margin-right: 35%" class="align-right">City Of Ideas</h1>
</nav>



<partial name="_CookieConsentPartial"/>

<div class="container">
    @RenderBody()
    <hr/>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center">
                    <p><a>City of Ideas</a> is een geregistreerde website, opgesteld volgens de laatste richtlijnen. </p>
                    <p class="h6">&copy; 2019 - City of Ideas</p>
                </div>
            </div>
        </div>
    </footer>
</div>


@RenderSection("Scripts", required: false)
</body>
</html>

PoC/UI-MVC/Views/Shared/_Layout_Super.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Identity
@using PoC.Areas.Identity.Data
@inject SignInManager<PoCIdentityUser> SignInManager
@inject UserManager<PoCIdentityUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - City of Ideas</title>

    <link rel="stylesheet" href="~/dist/site.css"/>
    <script type="module" src="~/dist/site.entry.js" defer></script>

</head>
<body>
<nav class="navbar navbar-expand sticky-top" id="navbar">
    <a class="navbar-brand" id="logo" href="/">
        <img alt="Brand"  src="/images/logo.png">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-default my-2 my-sm-0" type="submit">Zoek</button>
            </form>


            @if (!Context.Request.GetDisplayUrl().Contains("superadmin"))
            {
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Home">Start <span class="sr-only">(current)</span></a>
                </li>
                if (SignInManager.IsSignedIn(User) && User.IsInRole("Moderator"))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Moderator" asp-action="Index">Moderator</a>
                    </li>
                }
                if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin") || User.IsInRole("Superadmin")))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Project" asp-action="ManageProjects">Beheer Projecten</a>
                    </li>
                }
            }

            @if (Context.Request.GetDisplayUrl().Contains("superadmin"))
            {
                string orgLink = "";
                if (@TempData["Orglink"] != null)
                {
                    orgLink = @TempData["Orglink"].ToString();
                }
                string home = "/" + orgLink + "/home";
                string moderator = "/" + orgLink + "/Moderator";
                string manageProjecten = "/" + orgLink + "/projecten/ManageProjects";
                <li class="nav-item active">
                    <a class="nav-link" href="@home">Start <span class="sr-only">(current)</span></a>
                </li>

              
                if (SignInManager.IsSignedIn(User) && User.IsInRole("Moderator"))
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@moderator">Moderator</a>
                    </li>
                }
                if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin") || User.IsInRole("Superadmin")))
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@manageProjecten">Beheer Projecten</a>
                    </li>
                }
            }

            @if (SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="SuperAdmin" asp-action="ManageAdmins">Beheer Admins</a>
                </li>
            }
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="SuperAdmin" asp-action="ManageOrganisations">Beheer Organisaties</a>
                </li>
            }
        </ul>

        <partial name="_LoginPartial"/>
    </div>
</nav>

<partial name="_CookieConsentPartial"/>

<div class="container">
    @RenderBody()
    <hr/>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center">
                    <p><a>City of Ideas</a> is een geregistreerde website, opgesteld volgens de laatste richtlijnen. </p>
                    <p class="h6">&copy; 2019 - City of Ideas</p>
                </div>
            </div>
        </div>
    </footer>
</div>


@RenderSection("Scripts", required: false)
</body>
</html>