PoC/UI-MVC/Controllers/SuperadminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PoC.Areas.Identity.Data;
using PoC.BL.manager.organisation;
using PoC.BL.manager.project;
using PoC.BL.manager.user;
using PoC.Domain.organisation;
using PoC.Domain.project;
using PoC.Domain.user;
using PoC.Models;

namespace PoC.Controllers
{
    //added the policy for this type of user:
    [Authorize(Roles = "SuperAdmin")]
    [Route("[controller]")]
    public class SuperadminController : Controller
    {
        private readonly IOrganisationManager _mgr;
        private readonly IUserManager _userManager;
        private readonly UserManager<PoCIdentityUser> _identity;
        private readonly IProjectManager _projectManager;

        //File Management
        private readonly IHostingEnvironment _hostingEnvironment;


        public SuperadminController(IOrganisationManager mgr, IUserManager userManager,
            UserManager<PoCIdentityUser> identity, IHostingEnvironment hostingEnvironment,
            IProjectManager projectManager)
        {
            _mgr = mgr;
            _userManager = userManager;
            _identity = identity;
            _hostingEnvironment = hostingEnvironment;
            _projectManager = projectManager;
        }

        [Route("/superadmin/ManageAdmins")]
        public IActionResult ManageAdmins()
        {
            KeepCurrentOrganisation();

            var modtask = _identity.GetUsersInRoleAsync("Moderator");

            var admintask = _identity.GetUsersInRoleAsync("Admin");

            var superadmintask = _identity.GetUsersInRoleAsync("SuperAdmin");
            var users = _userManager.GetUsers();
            modtask.Wait();
            admintask.Wait();
            superadmintask.Wait();
            Console.WriteLine(admintask.Result.Count);
            Console.WriteLine(superadmintask.Result.Count);
            var admins = admintask.Result.Except(superadmintask.Result).Select(sa => sa.Id).ToList();
            Console.WriteLine(admins.Count);
            var retusers = new List<User>();
            foreach (var user in users)
            {
                if (admins.Contains(user.UserId))
                {
                    retusers.Add(user);
                }
            }


            return View(retusers);
        }

        [Route("/superadmin/demoteAdmin/{uid}")]
        public IActionResult DemoteAdmin(string uid)
        {
            var usrtask = _identity.GetUsersInRoleAsync("Admin");
            usrtask.Wait();
            var mods = usrtask.Result;
            PoCIdentityUser user = null;
            foreach (var mod in mods)
            {
                if (mod.Id == uid)
                {
                    user = mod;
                }
            }

            if (user is null)
            {
                return NotFound(uid);
            }

            _identity.RemoveFromRoleAsync(user, "Admin");
            return Ok(uid);
        }


        [Route("/superadmin/promoteAdmin/{uid}")]
        public IActionResult PromoteAdmin(string uid)
        {
            var usrtask = _identity.GetUsersInRoleAsync("Admin");
            usrtask.Wait();
            var mods = usrtask.Result;
            PoCIdentityUser user = null;
            foreach (var mod in mods)
            {
                if (mod.Id == uid)
                {
                    user = mod;
                }
            }

            if (user is null)
            {
                return NotFound(uid);
            }

            _identity.AddToRoleAsync(user, "SuperAdmin");
            return Ok(uid);
        }

        [HttpGet]
        [Route("/superadmin/CreateOrganisation")]
        public IActionResult CreateOrganisation()
        {
            KeepCurrentOrganisation();

            
            return View();
        }

        [HttpPost]
        [Route("/superadmin/CreateOrganisation")]
        public IActionResult CreateOrganisation(OrganisationModel organisationModel)
        {
            if (!ModelState.IsValid)
            {
                return View(organisationModel);
            }

            CreateDirectoriesOrganisation(organisationModel.Name);
            var uploadOrganisationPath =
                "organisations/" + organisationModel.Name.ToLower().Replace(" ", "") + "/organisation";

            var fileNameImage = "";
            if (ExtensionMethods.FileManagement.CheckFileExtension(organisationModel.ImageOrganisation.FileName))
            {
                var uploadImagePath = uploadOrganisationPath + "/images";
                fileNameImage = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,
                    uploadImagePath, organisationModel.ImageOrganisation);
            }

            var fileNameLogo = "";
            if (ExtensionMethods.FileManagement.CheckFileExtension(organisationModel.Logo.FileName))
            {
                var uploadLogoPath = uploadOrganisationPath + "/logos";
                fileNameLogo = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,
                    uploadLogoPath, organisationModel.Logo);
            }

            var fileNameDia1 = "";
            var uploadDiasPath = uploadOrganisationPath + "/dias";
            if (ExtensionMethods.FileManagement.CheckFileExtension(organisationModel.ImageOrganisation.FileName))
            {
                fileNameDia1 = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,
                    uploadDiasPath, organisationModel.Dia1);
            }

            var fileNameDia2 = "";
            if (ExtensionMethods.FileManagement.CheckFileExtension(organisationModel.ImageOrganisation.FileName))
            {
                fileNameDia2 = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,
                    uploadDiasPath, organisationModel.Dia2);
            }

            var fileNameDia3 = "";
            if (ExtensionMethods.FileManagement.CheckFileExtension(organisationModel.ImageOrganisation.FileName))
            {
                fileNameDia3 = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,
                    uploadDiasPath, organisationModel.Dia3);
            }

            _mgr.AddOrganisationViewModel(organisationModel.Name, fileNameImage, fileNameLogo, fileNameDia1,
                fileNameDia2,
                fileNameDia3, organisationModel.TelephoneNumber, organisationModel.Street, organisationModel.City,
                organisationModel.Country, organisationModel.Email,
                organisationModel.Description, organisationModel.FeaturedText, organisationModel.ZipCode,
                organisationModel.PrimaryColor, organisationModel.SecondaryColor, organisationModel.TertiaryColor);
            return RedirectToAction("ManageOrganisations");
        }

        [Route("/superadmin/manageorganisations")]
        public IActionResult ManageOrganisations()
        {
            KeepCurrentOrganisation();

            List<Organisation> orgs = _mgr.GetAllOrganisations();
            return View(orgs);
        }


        [Authorize(Roles = "SuperAdmin")]
        [Route("/superadmin/deleteorganisation/{id}")]
        public void DeleteOrganisation(string id)
        {
            Organisation organisation = _mgr.GetOrganisation(id);

            _mgr.CloseOrganisation(organisation);
        }

        [HttpGet]
        [Route("/superadmin/editorganisation/{id}")]
        public IActionResult EditOrganisation(string id)
        {
            KeepCurrentOrganisation();

            Organisation organisation = _mgr.GetOrganisation(id);

            

            return View(organisation);
        }

        [HttpPost]
        [Route("/superadmin/editorganisation/{id}")]
        public IActionResult EditOrganisation(string id, Organisation organisation, IFormFile imageOrganisation,
            IFormFile logoOrganisation, IFormFile dia1, IFormFile dia2, IFormFile dia3)
        {
            if (!ModelState.IsValid)
            {
                return View(organisation);
            }

            var uploadOrganisationPath =
                "organisations/" + organisation.Name.ToLower().Replace(" ", "") + "/organisation";
            var uploadImagePath = uploadOrganisationPath + "/images";
            var uploadLogoPath = uploadOrganisationPath + "/logos";
            var uploadDiasPath = uploadOrganisationPath + "/dias";

            AddFileToOrg(organisation, imageOrganisation, uploadImagePath, "image");
            AddFileToOrg(organisation, logoOrganisation, uploadLogoPath, "logo");
            AddFileToOrg(organisation, dia1, uploadDiasPath, "dia1");
            AddFileToOrg(organisation, dia2, uploadDiasPath, "dia2");
            AddFileToOrg(organisation, dia3, uploadDiasPath, "dia3");
            _mgr.ChangeOrganisation(organisation);

            return RedirectToAction("ManageOrganisations");
        }

        [HttpGet]
        [Route("/superadmin/copyorganisation/{id}")]
        public IActionResult CopyOrganisation(string id)
        {
            KeepCurrentOrganisation();

            Organisation organisation = _mgr.GetOrganisation(id);
            return View(organisation);
        }

        [Route("/superadmin/copyorganisation/{id}")]
        public IActionResult CopyOrganisation(Organisation organisation, string oldOrganisationName,
            IFormFile copyImageOrganisation,
            IFormFile copyLogoOrganisation, IFormFile copyDia1Organisation, IFormFile copyDia2Organisation,
            IFormFile copyDia3Organisation)
        {
            
            if (!ModelState.IsValid)
            {
                return View(organisation);
            }

PoC/UI-MVC/Views/SuperAdmin/CopyOrganisation.cshtml
@model PoC.Domain.organisation.Organisation

@{
    Layout = "_Layout_Super_Home";
}

<!DOCTYPE html>
<html>
<head>
    <title>Organisatie @Model.Name kopiëren </title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<br/>
<h2 class="text-center">Organisatie @Model.Name kopiëren</h2>
<br/>
<form id="formCopyOrganisation" asp-controller="Superadmin" asp-action="CopyOrganisation" method="post" enctype="multipart/form-data">
    <div id="textColor">
    <div class="form-group">

        <label asp-for="Name" class="control-label">Naam Kopie Platform</label>
        <input asp-for="Name" class="form-control" \>
        <span asp-validation-for="Name" class="text-danger"></span>

    </div>

    <input hidden id="oldOrganisationName" name="oldOrganisationName" value="@Model.Name" readonly/>
    <div class="form-group">

        <label asp-for="Description" class="control-label">Platform Beschrijving</label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="FeaturedText" class="control-label">Platform Featured Text</label>
        <textarea asp-for="FeaturedText" class="form-control"></textarea>
        <span asp-validation-for="FeaturedText" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="ZipCode" class="control-label">Postcode Zipcode</label>
        <input asp-for="ZipCode" class="form-control"/>
        <span asp-validation-for="ZipCode" class="text-danger"></span>

    </div>

    <h5 class="text-light"><u>Contactgegevens</u></h5>

    <div class="form-group">

        <label asp-for="TelephoneNumber" class="control-label">Gsm/Telefoonnummer</label>
        <input type="tel" pattern="[0-9]{9,10}" asp-for="TelephoneNumber" class="form-control"/>
        <span asp-validation-for="TelephoneNumber" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="Street" class="control-label">Straatnaam en huisnummer</label>
        <input asp-for="Street" class="form-control"/>
        <span asp-validation-for="Street" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="City" class="control-label">Stad</label>
        <input asp-for="City" class="form-control"/>
        <span asp-validation-for="City" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="Country" class="control-label">Land</label>
        <input asp-for="Country" class="form-control"/>
        <span asp-validation-for="Country" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="Email" class="control-label">Emailadres</label>
        <input type="email" asp-for="Email" class="form-control"/>
        <span asp-validation-for="Email" class="text-danger"></span>

    </div>

    <h5 class="text-light"><u>Afbeeldingen</u></h5>

    <div class="form-group">
        <label for="copyImageOrganisation" class="control-label">Platform Afbeelding</label>
        <button class="btn btn-danger showCopyImageOrg">Bewerk</button>
        <input asp-for="Image" value="@Model.Image" class="form-control" readonly/>
        <input id="copyImageOrganisation" type="file" accept=".jpg,.jpeg,.png" name="copyImageOrganisation" class="form-control" style="display: none"/>
        <span id="copyImageOrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
    </div>

    <div class="form-group">

        <label for="copyLogoOrganisation" class="control-label">Platform Logo</label>
        <button class="btn btn-danger showCopyLogoOrg">Bewerk</button>
        <input asp-for="Logo" value="@Model.Logo" class="form-control" readonly/>
        <input id="copyLogoOrganisation" type="file" accept=".jpg,.jpeg,.png" name="copyLogoOrganisation" class="form-control" style="display: none"/>
        <span id="copyLogoOrganisationValidation" class="text-danger" style="display: none">Kies een logo of zorg ervoor dat het logo van het type jpg of png is! </span>
    </div>

    <div class="form-group">
        <label for="copyDia1Organisation" class="control-label">Slideshow Afbeelding 1</label>
        <button class="btn btn-danger showCopyDia1Org">Bewerk</button>
        <input asp-for="Dia1" value="@Model.Dia1" class="form-control" readonly/>
        <input id="copyDia1Organisation" type="file" accept=".jpg,.jpeg,.png" name="copyDia1Organisation" class="form-control" style="display: none"/>
        <span id="copyDia1OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
    </div>

    <div class="form-group">
        <label for="copyDia2Organisation" class="control-label">Slideshow Afbeelding 2</label>
        <button class="btn btn-danger showCopyDia2Org">Bewerk</button>
        <input asp-for="Dia2" value="@Model.Dia2" class="form-control" readonly/>
        <input id="copyDia2Organisation" type="file" accept=".jpg,.jpeg,.png" name="copyDia2Organisation" class="form-control" style="display: none"/>
        <span id="copyDia2OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
    </div>

    <div class="form-group">
        <label for="copyDia3Organisation" class="control-label">Slideshow Afbeelding 3</label>
        <button class="btn btn-danger showCopyDia3Org">Bewerk</button>
        <input asp-for="Dia3" value="@Model.Dia3" class="form-control" readonly/>
        <input id="copyDia3Organisation" type="file" accept=".jpg,.jpeg,.png" name="copyDia3Organisation" class="form-control" style="display: none"/>
        <span id="copyDia3OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
    </div>

    <h5 class="text-light"><u>Optionele Styling</u></h5>
    <div class="form-group">

        <label asp-for="PrimaryColor" class="control-label">Primaire kleur </label>
        <input type="color" asp-for="PrimaryColor" value="@Model.PrimaryColor" class="col-1" readonly/>

    </div>

    <div class="form-group">

        <label asp-for="SecondaryColor" class="control-label">Secondaire kleur</label>
        <input type="color" asp-for="SecondaryColor" value="@Model.SecondaryColor" class="col-1" readonly/>

    </div>

    <div class="form-group">

        <label asp-for="TertiaryColor" class="control-label">Tertiaire kleur </label>
        <input type="color" asp-for="TertiaryColor" value="@Model.TertiaryColor" class="col-1" readonly/>

    </div>

    <div asp-validation-summary="All" class="text-danger"></div>
    <input id="copyOrganisationbtn" type="submit" value="Organisatie kopiëren"/>
    </div>
</form>
</body>
</html>

PoC/UI-MVC/Views/SuperAdmin/CreateOrganisation.cshtml
@model PoC.Models.OrganisationModel
@{

    Layout = "_Layout_Super_Home";
}

<!DOCTYPE html>

<html>
<head>
    <title>Nieuw Platform</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<br/>
<h2 class="text-center">Nieuw Platform Aanmaken</h2>

<form id="formCreateOrganisation" asp-controller="Superadmin" asp-action="CreateOrganisation" method="post" enctype="multipart/form-data">
    <div id="textColor">
        <div class="form-group">

            <label asp-for="Name" class="control-label">Platform Naam</label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="Description" class="control-label">Platform Beschrijving</label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="FeaturedText" class="control-label">Platform Featured Text</label>
            <textarea asp-for="FeaturedText" class="form-control"></textarea>
            <span asp-validation-for="FeaturedText" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="ZipCode" class="control-label">Platform Zipcode</label>
            <input type="number" asp-for="ZipCode" class="form-control"/>
            <span asp-validation-for="ZipCode" class="text-danger"></span>

        </div>

        <h5 class="text-light"><u>Contactgegevens</u></h5>

        <div class="form-group">

            <label asp-for="TelephoneNumber" class="control-label">Gsm/Telefoonnummer</label>
            <input type="tel" pattern="[0-9]{9,10}" asp-for="TelephoneNumber" class="form-control"/>
            <span asp-validation-for="TelephoneNumber" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="Street" class="control-label">Straatnaam en huisnummer</label>
            <input asp-for="Street" class="form-control"/>
            <span asp-validation-for="Street" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="City" class="control-label">Stad</label>
            <input asp-for="City" class="form-control"/>
            <span asp-validation-for="City" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="Country" class="control-label">Land</label>
            <input asp-for="Country" class="form-control"/>
            <span asp-validation-for="Country" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="Email" class="control-label">Emailadres</label>
            <input type="email" asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>

        </div>

        <h5 class="text-light"><u>Afbeeldingen</u></h5>

        <div class="form-group">

            <label asp-for="ImageOrganisation" class="control-label">Platform Afbeelding</label>
            <input id="createImageOrganisation" accept=".jpg,.jpeg,.png" asp-for="ImageOrganisation" class="form-control"/>
            <span id="createImageOrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
        </div>

        <div class="form-group">

            <label asp-for="Logo" class="control-label">Platform Logo</label>
            <input id="createLogoOrganisation" accept=".jpg,.jpeg,.png" asp-for="Logo" class="form-control"/>
            <span id="createLogoOrganisationValidation" class="text-danger" style="display: none">Kies een logo of zorg ervoor dat het logo van het type jpg of png is! </span>
        </div>

        <div class="form-group">

            <label asp-for="Dia1" class="control-label">Slideshow Afbeelding 1</label>
            <input id="createDia1Organisation" accept=".jpg,.jpeg,.png" asp-for="Dia1" class="form-control"/>
            <span id="createDia1OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
        </div>

        <div class="form-group">

            <label asp-for="Dia2" class="control-label">Slideshow Afbeelding 2</label>
            <input id="createDia2Organisation" accept=".jpg,.jpeg,.png" asp-for="Dia2" class="form-control"/>
            <span id="createDia2OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
        </div>

        <div class="form-group">

            <label asp-for="Dia3" class="control-label">Slideshow Afbeelding 3</label>
            <input id="createDia3Organisation" accept=".jpg,.jpeg,.png" asp-for="Dia3" class="form-control"/>
            <span id="createDia3OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
        </div>

        <h5 class="text-light"><u>Optionele Styling</u></h5>
        <div class="form-group">

            <label asp-for="PrimaryColor" class="control-label">Primaire kleur </label>
            <input type="color" asp-for="PrimaryColor" class="col-1"/>

        </div>

        <div class="form-group">

            <label asp-for="SecondaryColor" class="control-label">Secondaire kleur</label>
            <input type="color" asp-for="SecondaryColor" class="col-1"/>

        </div>

        <div class="form-group">

            <label asp-for="TertiaryColor" class="control-label">Tertiaire kleur </label>
            <input type="color" asp-for="TertiaryColor" class="col-1"/>

        </div>


        <div asp-validation-summary="All" class="text-danger"></div>
        <input class="btn btn-primary" id="createOrganisationbtn" type="submit" value="Platform opstellen"/>
    </div>
</form>

</body>
</html>

PoC/UI-MVC/Views/SuperAdmin/EditOrganisation.cshtml
@model PoC.Domain.organisation.Organisation

@{
    Layout = "_Layout_Super_Home";
}

<!DOCTYPE html>
<html>
<head>
    <title>Bewerk Organisatie @Model.Name</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<br/>
<h2 class="text-center">Organisatie @Model.Name bewerken</h2>
<br/>
<form id="formEditOrganisation" asp-controller="Superadmin" asp-action="EditOrganisation" method="post" enctype="multipart/form-data">
    <div id="textColor">
    <div class="form-group">

        <input type="hidden" asp-for="id" class="form-control" value="@Model.id" readonly/>

    </div>

    <div class="form-group">

        <label asp-for="Name" class="control-label">Platform Naam</label>
        <input asp-for="Name" class="form-control" readonly/>
        <span asp-validation-for="Name" class="text-danger"></span>

    </div>


    <div class="form-group">

        <label asp-for="Description" class="control-label">Platform Beschrijving</label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="FeaturedText" class="control-label">Platform Featured Text</label>
        <textarea asp-for="FeaturedText" class="form-control"></textarea>
        <span asp-validation-for="FeaturedText" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="ZipCode" class="control-label">Platform Zipcode</label>
        <input asp-for="ZipCode" class="form-control"/>
        <span asp-validation-for="ZipCode" class="text-danger"></span>

    </div>
    <h5 class="text-light"><u>Contactgegevens</u></h5>

    <div class="form-group">

        <label asp-for="TelephoneNumber" class="control-label">Gsm/Telefoonnummer</label>
        <input type="tel" pattern="[0-9]{9,10}" asp-for="TelephoneNumber" class="form-control"/>
        <span asp-validation-for="TelephoneNumber" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="Street" class="control-label">Straatnaam en huisnummer</label>
        <input asp-for="Street" class="form-control"/>
        <span asp-validation-for="Street" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="City" class="control-label">Stad</label>
        <input asp-for="City" class="form-control"/>
        <span asp-validation-for="City" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="Country" class="control-label">Land</label>
        <input asp-for="Country" class="form-control"/>
        <span asp-validation-for="Country" class="text-danger"></span>

    </div>

    <div class="form-group">

        <label asp-for="Email" class="control-label">Emailadres</label>
        <input type="email" asp-for="Email" class="form-control"/>
        <span asp-validation-for="Email" class="text-danger"></span>

    </div>
    <h5 class="text-light"><u>Afbeeldingen</u></h5>

    <div class="form-group">
        <label for="imageOrganisation" class="control-label">Platform Afbeelding</label>
        <button class="btn btn-danger showEditImageOrg">Bewerk</button>
        <input asp-for="Image" value="@Model.Image" class="form-control" readonly/>
        <input id="imageOrganisation" type="file" accept=".jpg,.jpeg,.png" name="imageOrganisation" class="form-control" style="display: none"/>
        <span id="imageOrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
    </div>

    <div class="form-group">

        <label for="logoOrganisation" class="control-label">Platform Logo</label>
        <button class="btn btn-danger showEditLogoOrg">Bewerk</button>
        <input asp-for="Logo" value="@Model.Logo" class="form-control" readonly/>
        <input id="logoOrganisation" type="file" accept=".jpg,.jpeg,.png" name="logoOrganisation" class="form-control" style="display: none"/>
        <span id="logoOrganisationValidation" class="text-danger" style="display: none">Kies een logo of zorg ervoor dat het logo van het type jpg of png is! </span>
    </div>

    <div class="form-group">
        <label for="dia1" class="control-label">Slideshow Afbeelding 1</label>
        <button class="btn btn-danger showEditDia1Org">Bewerk</button>
        <input asp-for="Dia1" class="form-control" readonly/>
        <input id="dia1Organisation" type="file" accept=".jpg,.jpeg,.png" name="dia1" class="form-control" style="display: none"/>
        <span id="dia1OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
    </div>

    <div class="form-group">
        <label for="dia2" class="control-label">Slideshow Afbeelding 2</label>
        <button class="btn btn-danger showEditDia2Org">Bewerk</button>
        <input asp-for="Dia2" class="form-control" readonly/>
        <input id="dia2Organisation" type="file" accept=".jpg,.jpeg,.png" name="dia2" class="form-control" style="display: none"/>
        <span id="dia2OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
    </div>


    <div class="form-group">
        <label for="dia3" class="control-label">Slideshow Afbeelding 3</label>
        <button class="btn btn-danger showEditDia3Org">Bewerk</button>
        <input asp-for="Dia3" class="form-control" readonly/>
        <input id="dia3Organisation" type="file" accept=".jpg,.jpeg,.png" name="dia3" class="form-control" style="display: none"/>
        <span id="dia3OrganisationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
    </div>

    <h5 class="text-light"><u>Optionele Styling</u></h5>
    <div class="form-group">

        <label asp-for="PrimaryColor" class="control-label">Primaire kleur </label>
        <input type="color" asp-for="PrimaryColor" class="col-1"/>

    </div>

    <div class="form-group">

        <label asp-for="SecondaryColor" class="control-label">Secondaire kleur</label>
        <input type="color" asp-for="SecondaryColor" class="col-1"/>

    </div>

    <div class="form-group">

        <label asp-for="TertiaryColor" class="control-label">Tertiaire kleur </label>
        <input type="color" asp-for="TertiaryColor" class="col-1"/>

    </div>

    <div asp-validation-summary="All" class="text-danger"></div>
    <input id="editOrganisationbtn" type="submit" value="Organisatie bewerken"/>
    </div>
</form>
</body>
</html>