PoC/UI-MVC/Models/IdeationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using PoC.Domain.datatype;

namespace PoC.Models
{
  public class IdeationViewModel : IValidatableObject
  {
    public IdeationType Type { get; set; }

    [Required]
    [StringLength(100, ErrorMessage = "Maximaal 100 tekens")]
    public string TitleIdeation { get; set; }

    [Required]
    [StringLength(2000, ErrorMessage = "Maximaal 2000 tekens")]
    public string DescriptionIdeation { get; set; }

    [DataType(DataType.Date)] public DateTime Begin { get; set; }
    [DataType(DataType.Date)] public DateTime End { get; set; }

    [Required(ErrorMessage = "Afbeelding verplicht mee te geven")]
    public IFormFile ImageIdeation { get; set; }

    public string BackgroundLink { get; set; }
    
    // De verschillende InputMogelijkheden die mogen meegegeven worden.
    public bool AllowImage { get; set; }
    public int NumberOfImages { get; set; }
    public bool ImageRequired { get; set; }
    public bool AllowVideo { get; set; }
    public int NumberOfVideos { get; set; }
    public bool VideoRequired { get; set; }
    public bool AllowVideoLink { get; set; }
    public bool VideoLinkRequired { get; set; }

    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
      List<ValidationResult> errors = new List<ValidationResult>();

      if (End < DateTime.Now)
      {
        errors.Add(new ValidationResult("Einddatum kan niet in het verleden liggen"));
      }

      if (End <= Begin)
      {
        errors.Add(new ValidationResult("Einddatum kan niet voor de Startdatum liggen"));
      }

      return errors;
    }
  }
}

PoC/UI-MVC/Controllers/IdeationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PoC.Areas.Identity.Data;
using PoC.BL.manager.input;
using PoC.BL.manager.InputMethod;
using PoC.BL.manager.project;
using PoC.BL.manager.user;
using PoC.Domain.input;
using PoC.Domain.inputmethod;

namespace PoC.Controllers
{
  [Route("{org}/[controller]")]
  public class IdeationController : Controller
  {
    private readonly IInputMethodManager _mgr;
    private readonly IProjectManager _projectManager;
    private readonly UserManager<PoCIdentityUser> _usermgr;
    private readonly IHostingEnvironment _hostingEnvironment;
    private readonly IUserManager _realUserManager;
    private readonly IInputManager _inputManager;

    public IdeationController(IInputMethodManager inputMethodManager, IProjectManager projectManager,
      UserManager<PoCIdentityUser> usermgr, IHostingEnvironment hostingEnvironment, IUserManager realUserManager,
      IInputManager inputManager)
    {
      _mgr = inputMethodManager;
      _projectManager = projectManager;
      _usermgr = usermgr;
      _hostingEnvironment = hostingEnvironment;
      _realUserManager = realUserManager;
      _inputManager = inputManager;
    }


    // GET
    [HttpGet]
    [Route("{id}")]
    public IActionResult Index(string id, string org)
    {
      ViewData["ideationImage"] = org;

      var ideation = _mgr.GetIdeation(id);
      _mgr.ChangeIdeation(ideation);
      Console.WriteLine(ideation);
      return View(ideation);
    }

    [Authorize]
    [Route("/Ideation/AddReactionToIdea")]
    public void AddReactionToIdea(string text, string ideaId)
    {
      var UserId = _usermgr.GetUserId(User);
      var user = _realUserManager.GetUser(UserId);
      var reactions = user.Inputs.ToList();
      Reaction reaction = new Reaction(_inputManager.GetIdea(ideaId), text, user);
      reaction.Time = DateTime.Now;
      reactions.Add(reaction);
      user.Inputs = reactions;
      _realUserManager.ChangeUser(user);

      Idea idea = _inputManager.GetIdea(ideaId);
      var reactionss = idea.Reactions.ToList();
      reactionss.Add(reaction);
      idea.Reactions = reactionss;
      _inputManager.ChangeIdea(idea);
      //_mgr.addReactionToIdea(ideaId, text.Trim(), _usermgr.GetUserId(User));
    }

    [Authorize]
    [Route("{id}/AddIdeaToIdeation")]
    public IActionResult AddIdeaToIdeation(string org, string titleIdea, string descriptionIdea, string ideationId,
      List<IFormFile> imageIdea, List<IFormFile> videoIdea, string videoLinkIdea)
      
    {
      var id = _usermgr.GetUserId(User);
      var user = _realUserManager.GetUser(id);
      Idea idea = new Idea(titleIdea, descriptionIdea);
      Ideation ideation = _mgr.GetIdeation(ideationId);
      if (ideation.AllowImage && imageIdea != null)
      {
        foreach (var i in imageIdea)
        {
          if (ExtensionMethods.FileManagement.CheckFileExtension(i.FileName))
          {
            var imageIdeaOrgString = "organisations/" + org + "/organisation/projects/ideations/ideas/images";
            var imageFileName = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,imageIdeaOrgString, i);
            var names = idea.ImageNames.ToList();
            names.Add(new Image(imageFileName));
            idea.ImageNames = names.AsEnumerable();
            
            _mgr.ChangeIdeation(ideation);
            
          }
        }
      }

      if (ideation.AllowVideo && videoIdea != null)
      {
        foreach (var vid in videoIdea)
        {
          if (Path.GetExtension(vid.FileName).Equals(".mp4") ||
              Path.GetExtension(vid.FileName).Equals(".webm") ||
              Path.GetExtension(vid.FileName).Equals(".ogg"))
          {
            var videoIdeaOrgString = "organisations/" + org + "/organisation/projects/ideations/ideas/videos";
            var videoFileName = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,videoIdeaOrgString, vid);

            var names = idea.VideoNames.ToList();
            names.Add(new Video(videoFileName));
            idea.VideoNames = names.AsEnumerable();
          }
        }
      }

      if (ideation.AllowVideoLink && videoLinkIdea != null)
      {
        var videoLinkName = videoLinkIdea.Substring(videoLinkIdea.LastIndexOf('=') + 1);
        idea.VideoLinkName = videoLinkName;
      }

      _mgr.AddIdeaToIdeation(ideationId, idea, _usermgr.GetUserId(User));


      return RedirectToAction("Index", new {id = ideationId});
    }

    [Route("/Ideation/addLikeToIdea/{ideaId}/{userId}")]
        public void AddLikeToIdea(string ideaId, string userId)
        {
            _mgr.AddLikeToIdea(ideaId, _realUserManager.GetUser(userId));
        }

    [Route("/Ideation/addShareToIdea")]
    public void AddShareToIdea(string ideaId)
    {
      _mgr.AddShareToIdea(ideaId);
    }

    [Route("/Ideation/AddShare")]
    public void AddShare(string id)
    {
      _mgr.AddShareToIdeation(id);
    }

    [HttpGet]
    [Route("edit/{id}")]
    public IActionResult EditIdeation(string id)
    {
      Ideation ideation = _mgr.GetIdeation(id);
      return View(ideation);
    }

        
    [HttpPost]
    [Route("edit/{id}")]
    public IActionResult EditIdeation(string org, Ideation ideation, IFormFile imageIdeation)
    {
      if (!ModelState.IsValid)
      {
        if (ModelState["Begin"].Errors.Count == 1)
        {
          ModelState["Begin"].Errors.Clear();
          ModelState.AddModelError("Begin", "Begindatum verplicht in te vullen");
}
        if (ModelState["End"].Errors.Count == 1)
        {
          ModelState["End"].Errors.Clear();
          ModelState.AddModelError("End", "Einddatum verplicht in te vullen");
        }

        return View(ideation);
      }

      if (imageIdeation != null)
      {
        if (ExtensionMethods.FileManagement.CheckFileExtension(imageIdeation.FileName))
        {
          {
            var ideationOrgString = "organisations/" + org + "/organisation/projects/ideations/images";
            var fileName = ExtensionMethods.FileManagement.UploadFile(_hostingEnvironment.WebRootPath,ideationOrgString, imageIdeation);
            ideation.ImageName = fileName;
          }
        }
      }

      _mgr.ChangeIdeation(ideation);
      return RedirectToAction("Index", new {id = ideation.Id});
    }


    [HttpPost]
    [Route("DeleteIdeation/{id}")]
    public void DeleteIdeation(string id)
    {
      Ideation ideation = _mgr.GetIdeation(id);


      _mgr.CloseIdeation(ideation);
    }

    [HttpPost]
    [Route("{id}/DeleteIdea")]
    public void DeleteIdea(string id, string ideaId)
    {
      Ideation ideation = _mgr.GetIdeation(id);
      _inputManager.RemoveIdea(ideaId);
    }
  }
}

PoC/UI-MVC/Controllers/apiControllers/IdeationsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using PoC.BL.manager.InputMethod;
using PoC.BL.manager.project;
using PoC.Domain.input;

namespace PoC.Controllers.apiControllers
{
    [Route("{org}/api/[controller]")]
    [ApiController]
    public class IdeationsController : ControllerBase
    {
        private readonly IInputMethodManager _manager;
        private readonly IProjectManager _projectManager;

        public IdeationsController(IInputMethodManager manager, IProjectManager projectManager)
        {
            _manager = manager;
            _projectManager = projectManager;
        }
        
        //GET /api/Ideations
        [HttpGet("{pid}")]
        [Route("getIdeationsFromProject/{pid}")]
        public IActionResult GetIdeation(string pid)
        {
            var project = _projectManager.GetProject(pid);
            var ideations = _manager.GetIdeationsFromProject(project);
            
            return Ok(ideations);
        }

        [HttpGet("{ideationId}")]
        [Route("getIdeation/{ideationId}")]
        public IActionResult GetIdeationSingle(string ideationId)
        {
            var ideation = _manager.GetIdeation(ideationId);
            if (ideation == null)
                return BadRequest();

            return Ok(ideation);
        }

        [HttpGet("{ideationId}")]
        [Route("getSharesFromIdeation/{ideationId}")]
        public IActionResult GetSharesFromIdeation(string ideationId)
        {
            var ideation = _manager.GetIdeation(ideationId);
            if (ideation == null)
            {
                return NoContent();
            }

            return Ok(ideation.Shares);
        }

        [HttpGet("{ideationId}")]
        [Route("getIdeasFromIdeation/{ideationId}")]
        public IActionResult GetIdeasFromIdeation(string ideationId)
        {
            var ideation = _manager.GetIdeation(ideationId);
            if (ideation == null)
            {
                return NoContent();
            }

            return Ok(ideation.Ideas);
        }

        [HttpPost]
        [Route("addShare/{ideationId}")]
        public IActionResult AddShare(string ideationId, [FromBody] Share share)
        {
            var ideation = _manager.GetIdeation(ideationId);
            var shares = ideation.Shares.ToList();
            shares.Add(share);
            ideation.Shares = shares;
            _manager.ChangeIdeation(ideation);
            return Ok(ideation);
        }

        [HttpPost]
        [Route("addIdeaToIdeation/{ideationId}")]
        public IActionResult AddIdeaToIdeation(string ideationId, Idea idea)
        {
            var ideation = _manager.GetIdeation(ideationId);
            var ideas = ideation.Ideas.ToList();
            ideas.Add(idea);
            ideation.Ideas = ideas;
            _manager.ChangeIdeation(ideation);
            return Ok(ideation);
        }
    }
}

PoC/UI-MVC/Views/Ideation/EditIdeation.cshtml
@model PoC.Domain.inputmethod.Ideation

@{
    Layout = "_Layout";
}

<!DOCTYPE html>
<html>
<head>
    <title>Bewerk Ideation @Model.TitleIdeation</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<br/>
<h2 class="text-center">Huidige Ideation bewerken</h2>

<form id="formEditIdeation" asp-controller="Ideation" asp-action="EditIdeation" asp-route-id="@Model.Id" method="post" enctype="multipart/form-data">
    <div id="textColor">

        <div class="form-group">

            <input type="hidden" asp-for="Id" class="form-control" value="@Model.Id" readonly/>

        </div>

        <div class="form-group">

            <label asp-for="Type">Ideation Type</label>
            <select asp-for="Type"
                    asp-items="@(new SelectList(Enum.GetValues(typeof(PoC.Domain.datatype.IdeationType))))"
                    class="form-control">
            </select>


        </div>

        <div class="form-group">

            <label asp-for="TitleIdeation" class="control-label">Titel Ideation</label>
            <input asp-for="TitleIdeation" class="form-control" value="@Model.TitleIdeation"/>
            <span asp-validation-for="TitleIdeation" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="DescriptionIdeation" class="control-label">Beschrijving</label>
            <textarea asp-for="DescriptionIdeation" class="form-control" value="@Model.DescriptionIdeation"> </textarea>
            <span asp-validation-for="DescriptionIdeation" class="text-danger"></span>

        </div>

        <div class="form-group">


            <label asp-for="Begin" class="control-label">Startdatum</label>
            <input asp-for="Begin" class="form-control" value="@Model.Begin.ToString("yyyy-MM-dd")"/>
            <span asp-validation-for="Begin" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="End" class="control-label">Einddatum</label>
            <input asp-for="End" class="form-control" value="@Model.End.ToString("yyyy-MM-dd")"/>
            <span asp-validation-for="End" class="text-danger"></span>

        </div>

        <div class="form-group">

            <label asp-for="BackgroundLink" class="control-label">(Optioneel) Link Extra Info</label>
            <input asp-for="BackgroundLink" type="url" class="form-control"/>

        </div>

        <div class="form-group">
            <label for="imageIdeation" class="control-label">Afbeelding</label>
            <button class="btn btn-danger showEditImageIdeation">Bewerk</button>
            <input asp-for="ImageName" value="@Model.ImageName" class="form-control" readonly/>
            <input id="imageIdeation" type="file" accept=".jpg,.jpeg,.png" name="imageIdeation" style="display: none" class="form-control"/>
            <span id="imageIdeationValidation" class="text-danger" style="display: none">Kies een afbeelding of zorg ervoor dat de afbeelding van het type jpg of png is! </span>
        </div>

        <div class="form-group">

            <h3>Configuratie van de ideeën</h3>

        </div>

        <div class="form-group">

            <div class="container">
                <table class="table" id="textColor">
                    <tr>
                        <td class="col-sm-3">Item</td>
                        <td class="col-sm-3">Toegelaten?</td>
                        <td class="col-sm-3">Hoeveel</td>
                        <td class="col-sm-3">Verplicht?</td>
                    </tr>
                    <tr>
                        <td class="col-sm-3">
                            <label class="form-control">Image</label>
                        </td>
                        <td class="col-sm-3">
                            <input type="checkbox" asp-for="AllowImage" value="true" checked="@Model.AllowImage" class="form-control checkImage"/>
                        </td>

                        @if (Model.AllowImage == true) {
                            <td class="col-sm-3">
                                <input type="number" asp-for="NumberOfImages" max="10" min="1" value="@Model.NumberOfImages" class="form-control imgDisable"/>
                            </td>
                            <td class="col-sm-3">
                                <input type="checkbox" asp-for="ImageRequired" value="true" checked="@Model.ImageRequired" class="form-control imgDisable"/>
                            </td>
                        }

                        @if (Model.AllowImage == false) {
                            <td class="col-sm-3">
                                <input type="number" asp-for="NumberOfImages" max="10" min="1" value="@Model.NumberOfImages" class="form-control imgDisable" disabled/>
                            </td>
                            <td class="col-sm-3">
                                <input type="checkbox" asp-for="ImageRequired" value="true" checked="@Model.ImageRequired" class="form-control imgDisable" disabled/>
                            </td>
                        }
                    </tr>
                    <tr>
                        <td class="col-sm-3">
                            <label class="form-control">Video</label>
                        </td>
                        <td class="col-sm-3">
                            <input type="checkbox" asp-for="AllowVideo" value="true" checked="@Model.AllowVideo" class="form-control checkVideo"/>
                        </td>
                        @if (@Model.AllowVideo == true) {
                            <td class="col-sm-3">
                                <input type="number" asp-for="NumberOfVideos" max="10" min="1" value="@Model.NumberOfVideos" class="form-control vidDisable"/>
                            </td>
                            <td class="col-sm-3">
                                <input type="checkbox" asp-for="VideoRequired" value="true" checked="@Model.VideoRequired" class="form-control vidDisable"/>
                            </td>
                        }

                        @if (@Model.AllowVideo == false) {
                            <td class="col-sm-3">
                                <input type="number" asp-for="NumberOfVideos" max="10" min="1" value="@Model.NumberOfVideos" class="form-control vidDisable" disabled/>
                            </td>
                            <td class="col-sm-3">
                                <input type="checkbox" asp-for="VideoRequired" value="true" checked="@Model.VideoRequired" class="form-control vidDisable" disabled/>
                            </td>
                        }
                    </tr>
                    <tr>
                        <td class="col-sm-3">
                            <label class="form-control">VideoLink</label>
                        </td>
                        <td class="col-sm-3">
                            <input type="checkbox" asp-for="AllowVideoLink" value="true" checked="@Model.AllowVideoLink" class="form-control checkVideoLink"/>
                        </td>
                        @if (Model.AllowVideoLink == true) {
                            <td class="col-sm-3">
                            </td>
                            <td class="col-sm-3">
                                <input type="checkbox" asp-for="VideoLinkRequired" value="true" checked="@Model.VideoLinkRequired" class="form-control vidLinkDisable"/>
                            </td>
                        }

                        @if (Model.AllowVideoLink == false) {
                            <td class="col-sm-3">
                            </td>
                            <td class="col-sm-3">
                                <input type="checkbox" asp-for="VideoLinkRequired" value="true" checked="@Model.VideoLinkRequired" class="form-control vidLinkDisable" disabled/>
                            </td>
                        }
                    </tr>
                </table>
            </div>

        </div>

        <div asp-validation-summary="All" class="text-danger"></div>
        <input id="editIdeationbtn" type="submit" value="Ideation bewerken"/>
    </div>
</form>
</body>
</html>